[package]
name = "core-mixer"
version = "0.1.0"
authors = ["Tibor Csóka"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook", "wasm"]
wasm = []

[dependencies]
async-std = { version = "1.12.0", features = ["attributes"] }
futures = "0.3.26"
futures-lite = "1.12.0"
rand = "0.8.5"
pin-project = "1.0.12"
# wasm specific
utils-misc = { path = "../../../utils/crates/utils-misc" }
getrandom = { version = "0.2.8", features = ["js"] }
gloo-timers = "0.2.6"       # WASM alternative for futures-timer
js-sys = "0.3.60"
wasm-bindgen = "0.2.83"
wasm-bindgen-futures = "0.4.33"

console_error_panic_hook = { version = "0.1.7", optional = true }
#wee_alloc = { version = "0.4.5", optional = true }

[dev-dependencies]
more-asserts = "0.3.1"
wasm-bindgen-test = "0.3.33"

[profile.release]
opt-level = "s"     # small code size
