[package]
name = "core-mixer"
version = "0.1.0"
authors = ["Tibor Csóka"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook", "wasm"]
wasm = []

[dependencies]
getrandom = { version = "0.2.8", features = ["js"] }
js-sys = "0.3.60"
priority-queue = "1.3.1"
rand = "0.8.5"
wasm-bindgen = "0.2.83"

console_error_panic_hook = { version = "0.1.7", optional = true }
#wee_alloc = { version = "0.4.5", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.33"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
