[workspace]

members = [
    "packages/real/crates/real-base",
    "packages/hoprd/crates/hoprd-misc",
    "packages/utils/crates/utils-metrics",
    "packages/utils/crates/utils-misc",
    "packages/core/crates/core-crypto"
]

[workspace.dependencies]
wasm-pack = "0.10.3"
wasm-opt = "0.110.2"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
#debug=true
