[workspace]

members = [
    "packages/real/crates/real-base",
    "packages/utils/crates/utils-metrics",
    "packages/utils/crates/utils-misc",
    "packages/core/crates/core-crypto"
]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
#debug=true
