[package]
name = "core-ethereum-connector"
version = "0.1.0"
authors = ["HOPR Association <tech@hoprnet.org>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook", "wasm"]
wasm = ["dep:wasm-bindgen", "dep:js-sys"]

[dependencies]
js-sys = { version = "0.3", optional = true }
lazy_static = "1.4"
thiserror = "1.0"
utils-misc = { path = "../../../utils/crates/utils-misc" }
utils-types = { path = "../../../utils/crates/utils-types" }
wasm-bindgen = { version = "0.2.83", optional = true}
wasm-bindgen-futures = "0.4"

console_error_panic_hook = { version = "0.1.7", optional = true }
#wee_alloc = { version = "0.4.5", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.33"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
