[package]
name = "core-crypto"
version = "0.1.0"
description = "Core cryptographic primitives and functions used in HOPR"
authors = ["HOPR Association <tech@hoprnet.org>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
aes = "0.8.1"
blake2 = "0.10.4"
chacha20 = "0.9.0"
digest = "0.10.3"
elliptic-curve = "0.12.0"
generic-array = "0.14.5"
getrandom = { version = "0.2.6", features = ["js"] }
hex-literal = "0.3"
hkdf = "0.12.3"
hmac = "0.12.1"
js-sys = "0.3.57"
k256 = { version = "0.11.2", features = ["arithmetic", "ecdh"] }
sha3 = "0.10.1"
static_assertions = "1.1.0"
typenum = "1.15.0"

wasm-bindgen = "0.2.80"

console_error_panic_hook = { version = "0.1.6", optional = true }
wee_alloc = { version = "0.4.5", optional = true }

[dev-dependencies]
hex-literal = "0.3"
wasm-bindgen-test = "0.3.13"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
