[package]
name = "core-crypto"
version = "0.1.0"
description = "Core cryptographic primitives and functions used in HOPR"
authors = ["HOPR Association <tech@hoprnet.org>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook", "wasm"]
wasm = []

[dependencies]
aes = "0.8.2"
blake2 = "0.10.4"
chacha20 = "0.9.0"
ctr = "0.9.1"
digest = "0.10.5"
elliptic-curve = "0.12.3"
generic-array = "0.14.6"
getrandom = { version = "0.2.8", features = ["js"] }
hex-literal = "0.3.4"
hkdf = "0.12.3"
hmac = "0.12.1"
js-sys = "0.3.60"
k256 = { version = "0.11.6", features = ["arithmetic", "ecdh"] }
rand = "0.8.5"
sha3 = "0.10.6"
static_assertions = "1.1.0"
typenum = "1.15.0"
thiserror = "1.0.37"

wasm-bindgen = "0.2.83"

console_error_panic_hook = { version = "0.1.7", optional = true }
#wee_alloc = { version = "0.4.5", optional = true }

[dev-dependencies]
hex-literal = "0.3.4"
wasm-bindgen-test = "0.3.33"

