[package]
name = "core-crypto"
version = "0.1.0"
description = "Core cryptographic primitives and functions used in HOPR"
authors = ["HOPR Association <tech@hoprnet.org>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
digest = "0.10.3"
blake2 = { version = "0.10.4", default-features = false }
sha2 = "0.10.2"
hkdf = "0.12.3"
hmac = "0.12.1"
getrandom = { version = "0.2.6", features = ["js"] }
group = "0.12.0"
elliptic-curve = "0.12.0"
k256 = { version = "0.11.2", features = ["arithmetic"] }

wasm-bindgen = "0.2.80"

console_error_panic_hook = { version = "0.1.6", optional = true }

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
#
# Unfortunately, `wee_alloc` requires nightly Rust when targeting wasm for now.
wee_alloc = { version = "0.4.5", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.13"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
